apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  DB_USER: {{ .Values.postgres.auth.username }}
  DB_PASSWORD: {{ .Values.postgres.auth.password }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret }}
